# Generated by Django 5.0.7 on 2024-07-16 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.post')),
                ('insp_link', models.CharField(blank=True, max_length=250)),
                ('seeking_pattern', models.BooleanField(default=False)),
            ],
            bases=('api.post',),
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.post')),
                ('instructions', models.CharField(max_length=1000)),
            ],
            bases=('api.post',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ref', models.CharField(max_length=250)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(choices=[('lace', 'Lace'), ('super_fine', 'Super Fine / Fingering / Sock'), ('fine', 'Fine / Sport / Baby'), ('light', 'Light / DK (Double Knitting) / Light Worsted'), ('medium', 'Medium / Worsted / Aran / Afghan'), ('bulky', 'Bulky / Chunky'), ('super_bulky', 'Super Bulky'), ('jumbo', 'Jumbo')], max_length=50)),
                ('yarn_type', models.CharField(choices=[('wool', 'Wool'), ('cotton', 'Cotton'), ('silk', 'Silk'), ('linen', 'Linen'), ('alpaca', 'Alpaca'), ('cashmere', 'Cashmere'), ('acrylic', 'Acrylic'), ('nylon', 'Nylon'), ('polyester', 'Polyester'), ('rayon', 'Rayon'), ('hand_dyed', 'Hand-Dyed'), ('self_stripling', 'Self-Striping'), ('variegated', 'Variegated'), ('gradient', 'Gradient'), ('metallic', 'Metallic'), ('boucle', 'Bouclé'), ('chenille', 'Chenille'), ('ribbon', 'Ribbon')], max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('beige', 'Beige')], max_length=50)),
                ('pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('crochet_hook', 'Crochet Hook'), ('stitch_marker', 'Stitch Marker'), ('scissors', 'Scissors'), ('measuring_tape', 'Measuring Tape'), ('tapestry_needle', 'Tapestry Needle'), ('blocking_board', 'Blocking Board')], max_length=40)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pattern')),
            ],
        ),
    ]
