# Generated by Django 5.0.7 on 2024-07-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yarn',
            old_name='pattern_id',
            new_name='pattern',
        ),
    ]
