# Generated by Django 5.0.7 on 2024-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pattern_id_yarn_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='seeking_pattern',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='instructions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool',
            field=models.CharField(blank=True, choices=[('crochet_hook', 'Crochet Hook'), ('stitch_marker', 'Stitch Marker'), ('scissors', 'Scissors'), ('measuring_tape', 'Measuring Tape'), ('tapestry_needle', 'Tapestry Needle'), ('blocking_board', 'Blocking Board')], max_length=40),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('beige', 'Beige')], max_length=50),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(blank=True, choices=[('lace', 'Lace'), ('super_fine', 'Super Fine / Fingering / Sock'), ('fine', 'Fine / Sport / Baby'), ('light', 'Light / DK (Double Knitting) / Light Worsted'), ('medium', 'Medium / Worsted / Aran / Afghan'), ('bulky', 'Bulky / Chunky'), ('super_bulky', 'Super Bulky'), ('jumbo', 'Jumbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='yarn_type',
            field=models.CharField(blank=True, choices=[('wool', 'Wool'), ('cotton', 'Cotton'), ('silk', 'Silk'), ('linen', 'Linen'), ('alpaca', 'Alpaca'), ('cashmere', 'Cashmere'), ('acrylic', 'Acrylic'), ('nylon', 'Nylon'), ('polyester', 'Polyester'), ('rayon', 'Rayon'), ('hand_dyed', 'Hand-Dyed'), ('self_stripling', 'Self-Striping'), ('variegated', 'Variegated'), ('gradient', 'Gradient'), ('metallic', 'Metallic'), ('boucle', 'Bouclé'), ('chenille', 'Chenille'), ('ribbon', 'Ribbon')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
