# Generated by Django 5.0.7 on 2024-07-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_inspiration_seeking_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='instructions',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
